server:
  port: 8000

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    client:
#      server-url:
#        defaultZone: localhost:8761 # eureka server 설정
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    ip-address: localhost
#    prefer-ip-address: true # ip address를 사용

spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devit_certification?serverTimezone=Asia/Seoul
    username: devit
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

#  application:
#    name: certification-service

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


cors:
  allowed-origins: http://localhost:8080
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: \*
  exposed-headers: Set-Cookie
  max-age: 3600

  # jwt secret key
jwt:
  secret: '8sknjlONPDTBqo39D4HLNqsQFfRcEdKCETOds'

  # secret Key
app:
  auth:
    tokenExpiry: 10800000            # 3시간
    refreshTokenExpiry: 604800000    # 7일